# Management
management:
  security:
    enabled: FALSE


# Server
server:
  port: 8081
  servlet:
    context-path: /springboot-crud/

# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 1234abcd
  jpa:
    generate-dll: TRUE

# Logging
logging:
  level:
    org:
      springframework: INFO
